core/urls.py
from django.urls import path
from . import views
from .views import HomePageView, SamplePageView

urlpatterns = [
    path('',  HomePageView.as_view(), name="home"),
    path('sample/', SamplePageView.as_view(), name="sample"),
]

pages/urls.py
from django.urls import path
from .views import PageListView, PageDetailView, PageCreate, PageUpdate, PageDelete

#Por que el cambio de url_patterns a page_patterns
pages_patterns = ([
    
    # Las urls convencionales son tipo:
    # path('pages', include('core.urls'))

    #Se devuelve cuna class bassed view como vista.asview()
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:slug>/', PageDetailView.as_view(), name='page'),
    
    #Se devuelve como una vista
    path('create/', PageCreate.as_view(), name='create'),
    path('update/<int:pk>/', PageUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PageDelete.as_view(), name='delete'),

], 'pages')

registration/urls.py
from django.urls import path
from .views import SignUpView, ProfileUpdate, EmailUpdate

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
    path('profile/', ProfileUpdate.as_view(), name="profile"),
    path('profile/email/', EmailUpdate.as_view(), name="profile_email"),
]

stores/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = "stores"

urlpatterns = [
    path('claroshop/', views.claroshop, name="claroshop"),
    path('linio/', views.linio, name="linio"),
    path('walmart/', views.walmart, name="walmart"),
]

webplayground/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.urls import pages_patterns
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    #Admin and pages
    path('pages/', include(pages_patterns)),
    path('admin/', admin.site.urls),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    #Stores
    path('stores/', include('stores.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Page(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

stores/models.py
from django.db import models

# Create your models here.

pages/forms.py
from django import forms
from .models import Page

class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ['title', 'content', 'order']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Titulo'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'order': forms.NumberInput(attrs={'class':'form-control'}),
        }
        labels = {
            'title':'', 'order':'', 'content':''
        }

core/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
import sqlite3

class HomePageView(TemplateView):
    
    def get(self, request, *args, **kwargs):
        with sqlite3.connect("stores.sqlite3") as conn:
            cursorObj = conn.cursor()
            
            #Products
            cursorObj.execute('SELECT count(id) FROM linio')
            products = cursorObj.fetchone()

            #Brands
            cursorObj.execute('SELECT count(DISTINCT brand) FROM linio')
            brands = cursorObj.fetchone()

            #Categories
            cursorObj.execute('SELECT COUNT(DISTINCT category) FROM linio')
            rows = cursorObj.fetchone()

            #Sellers
            cursorObj.execute('SELECT COUNT(DISTINCT seller) FROM linio')
            seller = cursorObj.fetchone()

            context = {
                'categories': rows[0],
                'products': products[0],
                'brands': brands[0],
                'seller': seller[0]
            }
            return render(request, "core/home.html", context)

class SamplePageView(TemplateView):
    template_name = "core/sample.html"

pages/views.py
# from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from .models import Page
from .forms import PageForm

#Esisten dos vistas basadas en clases
# Para cuando tengamos que devolver las instancias de un modelo (ListView)
# Para cuando tengamos que devolver una instancia de un modelo (DetailView)

# Esta clase se hereda a las otras clases que queramos combinar la autenticación
# Object es la clase base de todas las clases en python
class StaffRequiredMixin(object):
    ''' Este mixin requerirá que el susuario sea parte del staff '''
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)

class PageListView(ListView):
    model = Page

class PageDetailView(DetailView):
    model = Page

@method_decorator(staff_member_required, name='dispatch')
class PageCreate(CreateView):
    model = Page
    form_class = PageForm
    success_url = reverse_lazy('pages:pages')

@method_decorator(staff_member_required, name='dispatch')
class PageUpdate(UpdateView):
    model = Page
    form_class = PageForm
    template_name_suffix = '_update_form'
    
    def get_success_url(self):
        return reverse_lazy('pages:update', args=[self.object.id]) + '?ok'

@method_decorator(staff_member_required, name='dispatch')
class PageDelete(DeleteView):
    model = Page
    success_url = reverse_lazy('pages:pages')

stores/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import sqlite3


# Create your views here.
def claroshop(request):
    with sqlite3.connect("stores.sqlite3") as conn:
        cursorObj = conn.cursor()
        
        #Products
        cursorObj.execute('SELECT count(id) FROM claro')
        products = cursorObj.fetchone()

        #Brands
        cursorObj.execute('SELECT count(DISTINCT brand) FROM claro')
        brands = cursorObj.fetchone()

        #Categories
        cursorObj.execute('SELECT COUNT(DISTINCT category) FROM claro')
        rows = cursorObj.fetchone()

        #STOCK
        cursorObj.execute('SELECT COUNT(stock) FROM claropriceproducts WHERE stock > 0')
        stock_av = cursorObj.fetchone()

        context = {
            'categories': rows[0],
            'products': products[0],
            'brands': brands[0],
            'stock_av': stock_av[0],
        }
        return render(request, 'stores/claroshop.html', context)

def linio(request):
    with sqlite3.connect("stores.sqlite3") as conn:
        cursorObj = conn.cursor()
        
        #Products
        cursorObj.execute('SELECT count(sku) FROM claro')
        products = cursorObj.fetchone()

        #Brands
        cursorObj.execute('SELECT count(DISTINCT brand) FROM claro')
        brands = cursorObj.fetchone()

        #Categories
        cursorObj.execute('SELECT COUNT(DISTINCT category) FROM claro')
        rows = cursorObj.fetchone()

        context = {
            'categories': rows[0],
            'products': products[0],
            'brands': brands[0]
        }
        return render(request, 'stores/linio.html', context)

def walmart(request):
    titulo = 'Pagina base'
    context = {
        'titulo': titulo
    }
    return render(request, 'stores/walmart.html', context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
  </head>
  <body>
      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}"><strong>Compara</strong> Shop</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav">
              {% if not request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Acceder</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Registro</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link">Hola <strong>{{ user|title}}</strong></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">Perfil</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Salir</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      
      <!-- Contenido -->
      {% block content %}
        
      {% endblock %}

      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">
  {% if not request.user.is_authenticated %}
  <div style="padding-top:50px; text-align:center;">
    <h1>{{title}}</h1>
    <p class="lead">CBV, compara precios, perfiles y más</p>
  </div>
  {% else %}

  <div class="container">
    <div class="row">

      <!-- Side bar menu -->
      <div class="col-12 col-md-3">
        <h5 class="my-3"><strong>Stores</strong></h5>
        <div class="list-group">
          <a href="{% url 'stores:claroshop' %}" class="list-group-item">Claroshop</a>
          <a href="{% url 'stores:linio' %}" class="list-group-item">Linio</a>
          <a href="{% url 'stores:walmart' %}" class="list-group-item">Walmart</a>
        </div>
      </div>

      <div class="col-12 col-md-9">
        
        <div class="updated">
          <p>Última Actualización: 23 de Enero de 2020</p>
        </div>
        
        <!-- Start table -->
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Store</th>
              <th scope="col">CSV</th>
              <th scope="col">Productos</th>
              <th scope="col">Categorías</th>
              <th scope="col">Marcas</th>
              <th scope="col">Vendedores</th>

            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">Claroshop</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
              <td>@mdo</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">Linio</th>
              <td>Jacob</td>
              <td>{{products}}</td>
              <td>{{categories}}</td>
              <td>{{brands}}</td>
              <td>{{seller}}</td>
            </tr>
            <tr>
              <th scope="row">Walmart</th>
              <td>Larry</td>
              <td>the Bird</td>
              <td>@twitter</td>
              <td>@twitter</td>
              <td>@twitter</td>
            </tr>
          </tbody>
        </table>

        <!-- Search Bar -->
        <div class="compara">
          <div class="active-pink-3 active-pink-4 mb-4">
            <h5 class="encuentra"> <strong> ¡Encuentra tus productos favoritos! </strong></h5>
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </div>
        </div>

        <!-- Search results -->
        <div class="results">
          <div class="row">
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
            <div class="col-sm-3">
              <img src="https://picsum.photos/150" alt="..." class="img-thumbnail">
              <p>One of three columns</p>
              <p>Price</p>
            </div>
          </div>

          <!-- Navigation bar -->
          <nav aria-label="Page navigation example">
            <ul class="pagination">
              <li class="page-item"><a class="page-link" href="#">Previous</a></li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
          </nav>

        </div>

      </div>
    </div>

  </div>
  
  {% endif %}
</div>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}

  <div style="padding-top:50px; text-align:center;">
    <h1>Index: {{title}}</h1>
    <img src="{% static 'core/img/Larva.jpg'%}" class="img-fluid float-left" alt="Responsive image">
  </div>

  <div class="col-12 col-md-3">
    <div class="row">
      <div class="col">
        <h5 class="my-3">Tiendas</h5>
        <div class="list-group">
          <a href="/claroshop" class="list-group-item">Claroshop</a>
          <a href="/sanborns" class="list-group-item">Sanborns</a>
          <a href="/sears" class="list-group-item">Sears</a>
        </div>
      </div> 
    </div>
  </div>

  <div class="col col-md-9">  
    <p>Última Actualización: 23 de Enero de 2020</p>
  </div>

{% endblock %}

core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/includes/pages_menu.html
{% load static %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<link href="{% static 'pages/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Administrar</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:create' %}"><i>Crear página</i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:pages' %}"><i>Listar páginas</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

pages/templates/pages/page_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar <strong> "{{ object }}" </strong> ?</p>
                <input type="submit" class="btn btn-primary btn-block" value="Sí, borrar la página" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}

{% include 'pages/includes/pages_menu.html'%}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <h2 class="section-heading mb-4">{{page.title}}</h2>
        <div>
          {{page.content|safe}}
          {% if request.user.is_staff %}
            <p><a href="{% url 'pages:update' page.id %}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-3">
      <div class="col-md-9 mx-auto">
        <form action="" method="post">{% csrf_token %}
            <table>
                {{ form.as_p }}
            </table>
            <div class="text-center">
              <input type="submit" class="btn btn-primary btn-block" value="Crear página" />
            </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}

{% include 'pages/includes/pages_menu.html' %}

<main role="main">
  <div class="container mb-4">
    <!-- El nombre generico que le da es: object_list ó el nombre del modelo page_list -->
    {% for page in page_list|dictsort:"id" reversed %}
      <div class="row mt-3">
        <div class="col-md-9 mx-auto">
          <!-- Para el titulo -->
          <h2 class="mb-4">{{page.title}}</h2>
          <div>
            <!-- Para la descripción -->
            <p>{{page.content|striptags|safe|truncatechars:"200"}}</p>
            <!-- Para el link -->
            <p><a href="{% url 'pages:page' page.id page.title|slugify %}">Leer más</a>      
              <!-- Para los editables -->
              {% if request.user.is_staff %}
                | <a href="{% url 'pages:update' page.id %}">Editar</a>
                | <a href="{% url 'pages:delete' page.id %}">Borrar</a>
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

pages/templates/pages/page_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar Página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
        <div>
          {% if 'ok' in request.GET %}
            <p style="color:green"> 
              Página editada correctamente.
              <a href="{% url 'pages:page' page.id page.title|slugify %}">Haz click aquí para ver el resultado</a>.
            </p>
          {% endif %}
          <form action="" method="post">{% csrf_token %}
            <table>
                {{ form.as_p }}
            </table>
            <div class="text-center">
              <input type="submit" class="btn btn-primary btn-block" value="Actualizar página" />
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

stores/templates/stores/claroshop.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">

  <div class="container">
    <div class="row">

      <!-- Side bar menu -->
      <div class="col-12 col-md-3">
        <h5 class="my-3"><strong>Stores</strong></h5>
        <div class="list-group">
          <a href="{% url 'stores:claroshop' %}" class="list-group-item">Claroshop</a>
          <a href="{% url 'stores:linio' %}" class="list-group-item">Linio</a>
          <a href="{% url 'stores:walmart' %}" class="list-group-item">Walmart</a>
        </div>
      </div>

      <div class="col-12 col-md-9">
        <div class="updated">
          <h2>Claroshop</h2>
          <h6>Estratégia Comercial</h6>

          <p>{{stock_av}}</p>

        </div>
      </div>

      <div class="col-3 col-md-3">
        <div class="info-store">
          
          <h5 class="my-3"><strong>STATS</strong></h5>

          <h6 class="my-3"><strong>Products</strong></h6>
          <p>{{ products }}</p>

          <h6 class="my-3"><strong>Brands</strong></h6>
          <p>{{ brands }}</p>

          <h6 class="my-3"><strong>Categories</strong></h6>
          <p>{{ categories }}</p>

        </div>
      </div>

    </div>

  </div>

</div>

{% endblock %}

stores/templates/stores/linio.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">

  <div class="container">
    <div class="row">

      <!-- Side bar menu -->
      <div class="col-12 col-md-3">
        <h5 class="my-3"><strong>Stores</strong></h5>
        <div class="list-group">
          <a href="{% url 'stores:claroshop' %}" class="list-group-item">Claroshop</a>
          <a href="{% url 'stores:linio' %}" class="list-group-item">Linio</a>
          <a href="{% url 'stores:walmart' %}" class="list-group-item">Walmart</a>
        </div>
      </div>

      <div class="col-12 col-md-9">
        <div class="updated">
          <h2>Linio</h2>
          <h6>Estratégia Comercial</h6>

        </div>
      </div>

      <div class="col-3 col-md-3">
        <div class="info-store">
          
          <h5 class="my-3"><strong>STATS</strong></h5>

          <h6 class="my-3"><strong>Products</strong></h6>
          <p>{{ products }}</p>

          <h6 class="my-3"><strong>Brands</strong></h6>
          <p>{{ brands }}</p>

          <h6 class="my-3"><strong>Categories</strong></h6>
          <p>{{ categories }}</p>

        </div>
      </div>

    </div>

  </div>

</div>

{% endblock %}

stores/templates/stores/walmart.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">

  <div class="container">
    <div class="row">

      <!-- Side bar menu -->
      <div class="col-12 col-md-3">
        <h5 class="my-3"><strong>Stores</strong></h5>
        <div class="list-group">
          <a href="{% url 'stores:claroshop' %}" class="list-group-item">Claroshop</a>
          <a href="{% url 'stores:linio' %}" class="list-group-item">Linio</a>
          <a href="{% url 'stores:walmart' %}" class="list-group-item">Walmart</a>
        </div>
      </div>

      <div class="col-12 col-md-9">
        
        <div class="updated">
          <h2>Walmart</h2>
        </div>

      </div>
    </div>

  </div>

</div>

{% endblock %}